###############################################################################
# Start of stack config
###############################################################################
# Project Name
name: ${PROJECT_NAME}

networks:
  proxy:
    name: ${PROXY_NETWORK}
    external: true
  frontend:
    name: ${PROJECT_NAME}_frontend
    internal: false
    driver_opts:
      encrypted: "true"
  backend:
    name: ${PROJECT_NAME}_backend
    internal: true
    driver_opts:
      encrypted: "true"
  socket_proxy:
    name: ${PROJECT_NAME}_socket_proxy
    internal: true
    driver_opts:
      encrypted: "true"

# Include Agent services
include:
  - ./agent/compose.yaml